### ISSUE TITLE
The link to edit the page is missing the / at the start of the path

### ISSUE THREAD

**Issue by asecondwill** [wedevelopnl/silverstripe-admintoolbar#3]
for eg

https://mysite.ddev.siteadmin/pages/edit/show/1/

it worked correctly with SS4 , but upgrading site to SS5 and this module to dev-main, it is wrong, as above.

**Comment by erikfrerejean** [comment]
@asecondwill thanks for the report, we're working on a big update to the backend of this module and I guess that this issue will be resolved when that patch lands.

I'll keep this issue open for now, so we can revisit it once our updates come through on main.

**Comment by asecondwill** [comment]
cool, thank you.  your toolbar is very popular with our users!

**Comment by erikfrerejean** [comment]
That is great to hear!

We are aiming for a SS5 compatible stable release with the new front-end and features to be released end of march/starting of april.
