### ISSUE TITLE
Old (SS4) design was easier to use. 

### ISSUE THREAD

**Issue by asecondwill** [wedevelopnl/silverstripe-admintoolbar#4]
The new menu based system is a bit fiddly.  the bar accross the top was nice and simple in previous versions.

**Comment by erikfrerejean** [comment]
@asecondwill did you run this from the main branch? #1 contains a major rework of the front-end of this module which should resolve most UI/UX concerns.

**Comment by asecondwill** [comment]
Hi @erikfrerejean  

im using

"wedevelopnl/silverstripe-admintoolbar": "dev-main"

Note it also overlaps the debug bar. 

<img width="1271" alt="Screenshot 2024-02-19 at 10 51 57" src="https://github.com/wedevelopnl/silverstripe-admintoolbar/assets/156546/5d1b75e8-059d-4598-a495-3aa1533305d7">

**Comment by erikfrerejean** [comment]
@asecondwill thanks for the feedback.

The UI is indeed broken in `dev-main` at the moment but that will be resolved when #1 lands. The `ss-5-wip` branch contains the new frontend for the toolbar.

> Note it also overlaps the debug bar.
It is kinda hard to see on your screenshot, which debug bar do you mean? Or do you mean that you are running an other module aswell and that conflicts with the admin toolbar?

**Comment by asecondwill** [comment]
its this:

https://github.com/lekoala/silverstripe-debugbar

which is the grey square behind your bar on the right there

**Comment by erikfrerejean** [comment]
Thanks, I'll discuss this with our developers. At first glance I'm not sure whether there is a clear solution since we're "fighting" for the same real estate which makes sense because the bottom is imo the proper location for this kind of toolbars, so moving it back to the top by default just to resolve a conflict with a development module seems like a bad decision.

**Comment by erikfrerejean** [comment]
@asecondwill we feel that it is worth to look into a solution for the conflict with this module and have a couple of idea's on how to resolve it. I do not know yet when we'll land the patch for that but it will most likely be resolved before we'll release the first tagged version of a silverstripe 5 compatible release.
