### ISSUE TITLE
Namespace the css

### ISSUE THREAD

**Issue by asecondwill** [wedevelopnl/silverstripe-admintoolbar#5]
Your css has a reset which isnt namespaced.   is that avoidable when using tailwind?

**Comment by Dennisprins93** [comment]
Hi! Can you maybe better point out which reset you mean? Where do you see it? We only include some base styling from tailwind, all the rest we do by setting utility classes on each element.

**Comment by asecondwill** [comment]
it is setting styles on h1 for eg in the tailwind reset.   you maybe are not noticing because the rest of your site is tailwind? all the css  code from the module should be namespaced right?

**Comment by asecondwill** [comment]
this is in

` _resources/vendor/wedevelopnl/silverstripe-admintoolbar/client/dist/main.css?m=1704286185`

**Comment by Dennisprins93** [comment]
We see. This is now scheduled to be fixe in the next week. Thanks for reporting, Will!

**Comment by Dennisprins93** [comment]
Hi @asecondwill. We disabled the preflight, it's on the ss-5-wip branch. Can you let us know whether this is what you're looking for?
